./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Commander-Legends-Draft-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Kaldheim-Draft-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Kaldheim-Set-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Jumpstart-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Zendikar-Rising-Draft-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Zendikar-Rising-Set-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Core-2021-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Ikoria-Lair-of-Behemoths-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Theros-Beyond-Death-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Mystery-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Throne-of-Eldraine-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Core-2020-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Modern-Horizons-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/War-of-the-Spark-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Ravnica-Allegiance-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Ultimate-Masters-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Guilds-of-Ravnica-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Core-2019-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Battlebond-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Dominaria-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Masters-25-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Iconic-Masters-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Rivals-of-Ixalan-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Unstable-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Ixalan-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Hour-of-Devastation-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Amonkhet-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Aether-Revolt-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Kaladesh-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Conspiracy-Take-the-Crown-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Eldritch-Moon-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Eternal-Masters-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Shadows-over-Innistrad-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Oath-of-the-Gatewatch-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Battle-for-Zendikar-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Magic-Origins-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Modern-Masters-2015-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Dragons-of-Tarkir-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Fate-Reforged-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Khans-of-Tarkir-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Conspiracy-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Journey-into-Nyx-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Born-of-the-Gods-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Theros-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Dragon-s-Maze-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Gatecrash-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Return-to-Ravnica-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Avacyn-Restored-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Dark-Ascension-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Innistrad-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Mirrodin-Besieged-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Scars-of-Mirrodin-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Worldwake-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Zendikar-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Rise-of-the-Eldrazi-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Alara-Reborn-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Conflux-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Eventide-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Shadowmoor-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Champions-of-Kamigawa-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Fifth-Dawn-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Nemesis-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Mercadian-Masques-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Exodus-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Stronghold-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Tempest-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Weatherlight-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Visions-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Mirage-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Alliances-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Ice-Age-Booster-Box
./read-CM.sh https://www.cardmarket.com/en/Magic/Products/Booster-Boxes/Revised-Booster-Box
